name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.1.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
