name: Testing GitHub Action dependencies
on:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  directly-calling-github-actions:
    name: Directly calling github actions
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout
        with:
          persist-credentials: false

      - name: Use random "not github" action (last version is 0.0.2)
        uses: lint-md/github-action
       
  installing-npm-dependencies:
    runs-on: ubuntu-latest   
      steps:
        - uses: actions/setup-node@v3
        - run: npm install diogo-testing-npm-provenance
        
        
  installing-python-dependencies:
    runs-on: ubuntu-latest   
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
        - run: pip install pylint
  
  installing-go-dependencies:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-go
        - run: go get github.com/jung-kurt/gofpdf
  
