on: workflow_dispatch

permissions:
  contents: read

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@b818ac073677cb26a21e1dd897cbfe5a3726adf0 # v2
      - uses: uraimo/run-on-arch-action@a8003307a739516fdd80ee6d3da8924db811b8da # v2.5.0
